language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script:
  - asdf plugin-add kubeseal ./
  - asdf list-all kubeseal
  - asdf plugin-test kubeseal ./ --asdf-tool-version 0.7.0
os:
  - linux
  - osx
